services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: nobilesol
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: