server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
      enabled: false

logging:
  level:
    root: WARN
    com.suaempresa.seuprojeto: INFO